spring.datasource.url=jdbc:mysql://localhost:3306/village
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.hibernate.show-sql=true

server.port=8081


